### ISSUE TITLE
which version is this plugin supporting

### ISSUE THREAD

**Issue by gitGksgk** [yariplus/nodebb-plugin-modmin#1]
I can't have it work well in 1.10.12

**Comment by tom-rade** [comment]
Well yeah, it's only for the newest version (1.11.2 and maybe 1.11.1).

**Comment by gitGksgk** [comment]
alright thanks.
nodebb's plugin compatiability is a little ....

**Comment by yariplus** [comment]
I'll look into if 1.10 compatibility is possible.
